
module EngineyardAPI
  # Class to store application information
  class App
    ## App should be a hash provided by API calls, generated by the environment class.
    def initialize(app)
      @app=app
    end

    def app_id
      @app['id']
    end

    def name
      @app['name']
    end

    def repository
      @app['repository_uri']
    end

    def app_type
      @app['app_type_id']
    end

    def account_id
      @app['account']['id']
    end

    def account_name
      @app['account']['name']
    end

    def [](key)
      @app['key']
    end

    def zone
      @app['availability_zone']
    end

    def last_deploy=(deployment)
      @last_deploy=deployment
    end

    def last_deploy
      @last_deploy
    end
  end
end
