module EngineyardAPI
  # Store information on instances
  class Instance
    # Should be generated by environment class. Provide hash has argument
    def initialize(instance)
      @instance = instance
    end
    def instance_id
      @instance['id']
    end
    def status
      @instance['status']
    end
    def role
      @instance['role']
    end
    def name
      @instance['name']
    end
    def amazon_id
      @instance['amazon_id']
    end
    def public_hostname
      @instance['public_hostname']
    end
    def zone
      @instance['availability_zone']
    end
    def [](key)
      @instance['key']
    end
  end
end
